spring.application.name=expense_management

spring.datasource.url=jdbc:mysql://localhost:3306/codeswift_expense
spring.datasource.username=root
spring.datasource.password=9036477840
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true